Add Pages and Components architecture, installed axios
WildCodeSchool/2023-03-JS-TLSE-P2-quizilla pull request #3
Opened 2023-04-17 15:24 UTC by Swadek

2023-04-17 15:29 UTC, ArthurHtbk requested changes
Attention code mort !

2023-04-18 07:30 UTC, 6sous approved these changes

2023-04-18 09:12 UTC, 6sous approved these changes

2023-04-18 09:41 UTC, 6sous approved these changes

2023-04-18 10:17 UTC, closed without merging